package com.panduka.ncms.helpers;

import com.panduka.ncms.dto.HospitalDTO;
import com.panduka.ncms.dto.PatientDTO;
import com.panduka.ncms.dto.UserDTO;
import com.panduka.ncms.dto.impl.HospitalDTOImpl;
import com.panduka.ncms.dto.impl.PatientDTOImpl;
import com.panduka.ncms.dto.impl.UserDTOImpl;
import com.panduka.ncms.entity.Hospital;
import com.panduka.ncms.entity.Patient;
import com.panduka.ncms.entity.PatientQueue;
import com.panduka.ncms.entity.User;

import java.util.ArrayList;
import java.util.List;

public class Mapper {
    public  static Object convertToEntityObject(Object dto) {

        if( dto instanceof HospitalDTOImpl){
            Hospital hospitalEntity = new Hospital();
            HospitalDTO hospitalDTO = (HospitalDTO) dto;

            hospitalEntity.setName( hospitalDTO.getName());
            hospitalEntity.setLocationY( hospitalDTO.getY());
            hospitalEntity.setLocationX( hospitalDTO.getX());
            hospitalEntity.setChiefDoctor((User) Mapper.convertToEntityObject( hospitalDTO.getChiefDoctor()));
            hospitalEntity.setAvailBeds( hospitalDTO.getNoOfBeds() );

            //id is generated by the hibernate itself
            //build date is only needed when creating the hospital

            return hospitalEntity;
        }
        if( dto instanceof PatientDTOImpl){

        }
        if( dto instanceof UserDTOImpl){

        }
        if( dto instanceof PatientDTOImpl){

        }

        return null;
    }

    public static Object convertToDTO(Object entity) {
        if( entity instanceof Hospital){
            HospitalDTO hospitalDTO = new HospitalDTOImpl();
            Hospital hospitalEntity = (Hospital) entity;
            List<PatientDTO> patientListDTO= new ArrayList<>();

            //need to come up with another way to convert patientEntity list to patientDTOList
            if( hospitalEntity.getPatientList() != null){
                for( Patient p: hospitalEntity.getPatientList()){
                    PatientDTO patientDTO = (PatientDTO) p;
                    patientListDTO.add( patientDTO);
                }
            }

            hospitalDTO.setId( hospitalEntity.getId());
            hospitalDTO.setName( hospitalEntity.getName());
            hospitalDTO.setDistrictName( hospitalEntity.getDistrict());
            hospitalDTO.setX( hospitalEntity.getLocationX());
            hospitalDTO.setY( hospitalEntity.getLocationY());
            hospitalDTO.setNoOfBeds( hospitalEntity.getAvailBeds());
            hospitalDTO.setPatients( patientListDTO);
            hospitalDTO.setChiefDoctor( (UserDTO) Mapper.convertToDTO( hospitalEntity.getChiefDoctor()));

            return hospitalDTO;
        }
        if( entity instanceof User){
            UserDTO userDTO = new UserDTOImpl();
            User userEntity = ( User) entity;

            userDTO.setId( userEntity.getId());
            userDTO.setFirstName( userEntity.getFirstName());
            userDTO.setLastName( userEntity.getLastName());
            //userDTO.setPassword();
            //userDTO.setUsername();
            userDTO.setRole( userEntity.getRole());

            return userDTO;
        }
        if( entity instanceof Patient){

        }
        if( entity instanceof PatientQueue){

        }


        return null;
    }

}
